# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99c0e05e10b96ca73af4e770004943d0491996fcfda31206a8e133984da3e0a9f081d5dcd6646260b578c20de0c5258255d82525ea4279922649930e930620fc

test:
  secret_key_base: 317c2fd224b70d9a2418669b092dfe0469bce1639ab671fe699d6da9fb7071424bfb2fc1c7220603d880438aa5de956332689d9bcca330d819df9d659c133ec1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
